(()=>{const $=id=>document.getElementById(id),KEY='sticker-village-mvp-v1';const defaults=[['life','Daily Life','☕','note',18,27,-5],['travel','Travel Notes','📷','photo',42,19,4],['ideas','Little Ideas','✦','star',68,31,3],['reading','Reading Room','📚','book',27,62,2],['projects','Projects','💻','camera',63,63,-4]];let data;try{data=JSON.parse(localStorage.getItem(KEY))}catch{}if(!data)data={stickers:defaults.map(a=>({id:a[0],name:a[1],icon:a[2],kind:a[3],x:a[4],y:a[5],rot:a[6],posts:[],description:''})),posts:[],next:1};let edit=false,drag=null,timer;
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(data))}catch{}};
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('toast').classList.remove('show'),2500)}
function render(){$('stickers').innerHTML='';$('count').textContent=data.posts.length+' posts';$('empty').classList.toggle('hidden',data.stickers.length>0);data.stickers.forEach(s=>{let b=document.createElement('button');b.className=`sticker kind-${s.kind||'note'} ${edit?'editing':''}`;b.style.left=s.x+'%';b.style.top=s.y+'%';b.style.setProperty('--rot',(s.rot||0)+'deg');b.dataset.id=s.id;b.innerHTML=`<span class="ico">${esc(s.icon)}</span><strong>${esc(s.name)}</strong><small>${(s.posts||[]).length} RECORDS</small>`;if(edit){b.addEventListener('pointerdown',e=>startDrag(e,b,s));b.addEventListener('click',e=>{if(b.dataset.moved==='1'){e.preventDefault();b.dataset.moved='0'}})}else b.onclick=()=>openPanel(s);$('stickers').appendChild(b)});$('editBtn').textContent=edit?'편집 완료':'편집 모드'}
function startDrag(e,b,s){if(e.button!==0&&e.pointerType==='mouse')return;drag={b,s,x:e.clientX,y:e.clientY,l:s.x,t:s.y,m:false};b.setPointerCapture?.(e.pointerId);b.onpointermove=ev=>{if(!drag)return;let r=$('canvas').getBoundingClientRect(),dx=(ev.clientX-drag.x)/r.width*100,dy=(ev.clientY-drag.y)/r.height*100;if(Math.abs(dx)+Math.abs(dy)>1)drag.m=true;b.style.left=Math.max(1,Math.min(87,drag.l+dx))+'%';b.style.top=Math.max(5,Math.min(80,drag.t+dy))+'%'};b.onpointerup=b.onpointercancel=()=>{if(!drag)return;if(drag.m){s.x=parseFloat(b.style.left);s.y=parseFloat(b.style.top);b.dataset.moved='1';save()}b.onpointermove=null;drag=null}}
function openPanel(s){$('panelTitle').textContent=s.name;$('panelMeta').textContent=(s.posts||[]).length+'개 기록 · '+(s.description||'스티커에 연결된 콘텐츠');let ps=(s.posts||[]).slice().sort((a,b)=>(b.date||'').localeCompare(a.date||''));$('posts').innerHTML=ps.length?ps.map(p=>`<article class="post"><time>${esc(p.date||'날짜 없음')} · ${esc(p.source||'기록')}</time><h3>${esc(p.title)}</h3><p>${esc((p.excerpt||'').slice(0,400))}</p>${p.url?`<a href="${esc(p.url)}" target="_blank" rel="noopener">원문 열기 ↗</a>`:''}</article>`).join(''):'<p>아직 기록이 없습니다. 파일을 가져오거나 새 스티커를 만들어보세요.</p>';$('panel').classList.add('open')}
function closePanel(){$('panel').classList.remove('open')}
function openImport(){$('import').classList.add('open');$('status').textContent=''}
function closeImport(){$('import').classList.remove('open')}
function icon(kind){return({note:'📝',photo:'📷',flower:'🌼',book:'📚',camera:'📸',star:'✦'})[kind]||'✦'}
function categorize(p){let t=(p.title+' '+p.excerpt).toLowerCase(),id=/여행|travel|제주|도쿄|trip/.test(t)?'travel':/개발|코드|program|github|api|react|프로젝트|tech/.test(t)?'projects':/책|독서|공부|학습|study|book/.test(t)?'reading':/생각|아이디어|idea|회고|느낌/.test(t)?'ideas':'life';let s=data.stickers.find(x=>x.id===id);if(!s){s={id,name:id==='travel'?'Travel Notes':id==='projects'?'Projects':id==='reading'?'Reading Room':id==='ideas'?'Little Ideas':'Daily Life',icon:icon(id==='projects'?'camera':id==='reading'?'book':id==='ideas'?'star':'photo'),kind:id==='projects'?'camera':id==='reading'?'book':id==='ideas'?'star':'photo',x:48,y:45,rot:2,posts:[]};data.stickers.push(s)}return s}
function addPost(p){let post={id:'p'+data.next++,title:p.title||'제목 없는 기록',excerpt:p.excerpt||'',date:p.date||'',url:p.url||'',source:p.source||'가져온 기록'};data.posts.push(post);categorize(post).posts.push(post)}
function md(text,name){return text.split(/\n(?=#{1,3}\s)/g).filter(x=>x.trim()).map(chunk=>{let lines=chunk.split(/\r?\n/),title=(lines.find(l=>/^#{1,6}\s/.test(l))||'').replace(/^#{1,6}\s*/,'').trim()||name.replace(/\.(md|markdown|txt)$/i,'').replace(/[_-]/g,' '),date=(name+' '+chunk.slice(0,300)).match(/20\d{2}[-/.]\d{1,2}[-/.]\d{1,2}/),body=lines.filter(l=>!/^#{1,6}\s/.test(l)).join('\n').replace(/!\[[^\]]*\]\([^)]*\)/g,'[이미지]').replace(/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/g,'$1').replace(/[*_`>#]/g,'').trim(),url=chunk.match(/\]\((https?:\/\/[^)]+)\)/);return{title,excerpt:body.slice(0,450),date:date?date[0].replace(/[/.]/g,'-'):'',url:url?url[1]:'',source:'Markdown/Notion'}})}
function html(text,name){let d=new DOMParser().parseFromString(text,'text/html'),body=(d.body?.innerText||'').trim(),date=(name+' '+body.slice(0,300)).match(/20\d{2}[-/.]\d{1,2}[-/.]\d{1,2}/);return[{title:d.querySelector('h1')?.textContent?.trim()||d.title||name.replace(/\.html?$/i,''),excerpt:body.slice(0,500),date:date?date[0].replace(/[/.]/g,'-'):'',url:d.querySelector('a[href^="http"]')?.href||'',source:'HTML/Notion'}]}
async function importFiles(files){let added=0,skip=0;$('status').textContent='파일을 읽는 중…';for(let f of files){try{if(/\.zip$/i.test(f.name)){if(!window.JSZip)throw Error('ZIP 읽기 라이브러리 로딩 실패');let z=await JSZip.loadAsync(f),entries=Object.values(z.files).filter(x=>!x.dir&&!x.name.startsWith('__MACOSX/')&&/\.(md|markdown|html?|txt)$/i.test(x.name));for(let ent of entries){let t=await ent.async('string'),arr=/\.(md|markdown|txt)$/i.test(ent.name)?md(t,ent.name):html(t,ent.name);arr.forEach(p=>{p.source='Notion export';addPost(p);added++})}}else{let t=await f.text(),arr=/\.(md|markdown|txt)$/i.test(f.name)?md(t,f.name):/\.(html?)$/i.test(f.name)?html(t,f.name):/\.json$/i.test(f.name)?(()=>{let j=JSON.parse(t);return(Array.isArray(j)?j:j.posts||j.results||[j]).map(x=>({title:x.title||x.name||f.name,excerpt:x.content||x.body||x.text||x.description||'',date:x.date||x.created_time||x.publishedAt||'',url:x.url||'',source:'JSON'}))})():null;if(!arr){skip++;continue}arr.forEach(addPost);added++}}catch(e){console.error(e);skip++}}save();render();closeImport();toast(added?`${added}개 기록을 가져왔습니다${skip?' · 일부 파일 건너뜀':''}`:'가져올 수 있는 기록이 없습니다')}
$('importBtn').onclick=openImport;$('emptyImport').onclick=openImport;$('closeImport').onclick=closeImport;$('importScrim').onclick=closeImport;$('choose').onclick=()=>$('files').click();$('files').onchange=e=>importFiles(e.target.files);$('drop').ondragover=e=>{e.preventDefault();$('drop').style.background='#f1eadb'};$('drop').ondragleave=()=>$('drop').style.background='';$('drop').ondrop=e=>{e.preventDefault();importFiles(e.dataTransfer.files)};$('editBtn').onclick=()=>{edit=!edit;render();toast(edit?'스티커를 드래그해 배치하세요':'배치를 저장했습니다')};$('add').onclick=()=>$('newDialog').showModal();$('newForm').onsubmit=e=>{e.preventDefault();let k=$('newKind').value;data.stickers.push({id:'custom'+Date.now(),name:$('newName').value,icon:icon(k),kind:k,x:38+Math.random()*20,y:35+Math.random()*20,rot:Math.random()*8-4,description:$('newDesc').value,posts:[]});save();render();$('newDialog').close();$('newForm').reset();toast('스티커를 붙였습니다')};$('reset').onclick=()=>{if(confirm('기본 배치로 되돌릴까요? 기록은 유지됩니다.')){let pos={life:[18,27],travel:[42,19],ideas:[68,31],reading:[27,62],projects:[63,63]};data.stickers.forEach(s=>{if(pos[s.id]){s.x=pos[s.id][0];s.y=pos[s.id][1]}});save();render()}};$('close').onclick=closePanel;$('scrim').onclick=closePanel;document.addEventListener('keydown',e=>{if(e.key==='Escape'){closePanel();closeImport()}});$('timeline').oninput=e=>{let v=+e.target.value;$('timeLabel').textContent=v===100?'전체 기록':v+'% 시점';let dates=data.posts.map(p=>p.date).filter(Boolean).sort();if(!dates.length)return;let cutoff=dates[Math.floor((dates.length-1)*v/100)];data.stickers.forEach(s=>{let el=document.querySelector(`[data-id="${s.id}"]`);if(el){let has=(s.posts||[]).some(p=>!p.date||p.date<=cutoff);el.style.opacity=has||v===100?'1':'.35'}})};render()})();